cluster.name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}

network.host: ${NETWORK_HOST}

path.data: /data/data

bootstrap.memory_lock: true

http:
  enabled: ${HTTP_ENABLE}
  compression: true

cloud:
  kubernetes:
    service: ${DISCOVERY_SERVICE}
    namespace: ${NAMESPACE}

discovery.zen.hosts_provider: kubernetes

plugin.mandatory: discovery-kubernetes
